Repository OCA/knowledge, pull requests merged in 2020-11, with the labels that each got.

#258 [12.0][FIX] document_page_approval: fix strings
  document_page_approval/i18n/document_page_approval.pot
  document_page_approval/models/document_page_history.py
Labels: approved, bot is merging ⏳, ready to merge

#269 [IMP] Apply template
  .copier-answers.yml
  .gitignore
  .pre-commit-config.yaml
  .prettierrc.yml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  CONTRIBUTING.md
  LICENSE
  README.md
  oca_dependencies.txt
Labels: approved

#268 [13.0][FIX] document_page: fix multicompany rules
  document_page/security/document_page_security.xml
  document_page/views/document_page_category.xml
Labels: approved, bot is merging ⏳
