Repository OCA/knowledge, pull requests merged in 2020-07, with the labels that each got.

#242 [12.0][MIG] document_page_reference
  document_page_reference/README.rst
  document_page_reference/__init__.py
  document_page_reference/__manifest__.py
  document_page_reference/i18n/document_page_reference.pot
  document_page_reference/models/__init__.py
  document_page_reference/models/document_page.py
  document_page_reference/readme/CONTRIBUTORS.rst
  document_page_reference/readme/DESCRIPTION.rst
  document_page_reference/readme/USAGE.rst
  document_page_reference/static/description/icon.png
  document_page_reference/static/description/index.html
  document_page_reference/static/src/js/editor.js
  document_page_reference/tests/__init__.py
  document_page_reference/tests/test_document_reference.py
  document_page_reference/views/assets.xml
  document_page_reference/views/document_page.xml
  document_page_reference/views/report_document_page.xml
Labels: approved, bot is merging ⏳, ready to merge

#238 [FIX] document_page: duplicate page with content
  document_page/models/document_page.py
Labels: approved, bot is merging ⏳

#245 Fix document_page: Required impossible. Protected method needed
  document_page/models/document_page.py
Labels: approved, bot is merging ⏳, bug, needs review, ready to merge

#251 [IMP] document_page: Add button box
  document_page/views/document_page.xml
Labels: approved, bot is merging ⏳, enhancement, needs review, ready to merge

#221 [12.0][MIG] attachment_preview
  .travis.yml
  attachment_preview/README.rst
  attachment_preview/__init__.py
  attachment_preview/__manifest__.py
  attachment_preview/i18n/attachment_preview.pot
  attachment_preview/i18n/de.po
  attachment_preview/i18n/es.po
  attachment_preview/i18n/it.po
  attachment_preview/i18n/nl.po
  attachment_preview/i18n/pt_PT.po
  attachment_preview/i18n/sl.po
  attachment_preview/i18n/zh_CN.po
  attachment_preview/models/__init__.py
  attachment_preview/models/ir_attachment.py
  attachment_preview/readme/CONTRIBUTORS.rst
  attachment_preview/readme/CREDITS.rst
  attachment_preview/readme/DESCRIPTION.rst
  attachment_preview/readme/INSTALL.rst
  attachment_preview/readme/USAGE.rst
  attachment_preview/static/description/icon.png
  attachment_preview/static/description/index.html
  attachment_preview/static/description/screenshot-paginator.png
  attachment_preview/static/description/screenshot-split.png
  attachment_preview/static/lib/ViewerJS/compatibility.js
  attachment_preview/static/lib/ViewerJS/example.local.css
  attachment_preview/static/lib/ViewerJS/images/kogmbh.png
  attachment_preview/static/lib/ViewerJS/images/nlnet.png
  attachment_preview/static/lib/ViewerJS/images/texture.png
  attachment_preview/static/lib/ViewerJS/images/toolbarButton-download.png
  attachment_preview/static/lib/ViewerJS/images/toolbarButton-fullscreen.png
  attachment_preview/static/lib/ViewerJS/images/toolbarButton-menuArrows.png
  attachment_preview/static/lib/ViewerJS/images/toolbarButton-pageDown.png
  attachment_preview/static/lib/ViewerJS/images/toolbarButton-pageUp.png
  attachment_preview/static/lib/ViewerJS/images/toolbarButton-presentation.png
  attachment_preview/static/lib/ViewerJS/images/toolbarButton-zoomIn.png
  attachment_preview/static/lib/ViewerJS/images/toolbarButton-zoomOut.png
  attachment_preview/static/lib/ViewerJS/index.html
  attachment_preview/static/lib/ViewerJS/pdf.js
  attachment_preview/static/lib/ViewerJS/pdf.worker.js
  attachment_preview/static/lib/ViewerJS/pdfjsversion.js
  attachment_preview/static/lib/ViewerJS/text_layer_builder.js
  attachment_preview/static/lib/ViewerJS/ui_utils.js
  attachment_preview/static/lib/ViewerJS/webodf.js
  attachment_preview/static/src/js/attachment_preview.js
  attachment_preview/static/src/js/viewerjs_tweaks.js
  attachment_preview/static/src/scss/attachment_preview.scss
  attachment_preview/static/src/xml/attachment_preview.xml
  attachment_preview/templates/assets.xml
  attachment_preview/tests/__init__.py
  attachment_preview/tests/test_attachment_preview.py
Labels: bot is merging ⏳

#257 [FIX][13.0] retrive 12.0 behaviours in category creation without content
  document_page/views/document_page_category.xml
Labels: approved, bot is merging ⏳, ready to merge
