Repository OCA/knowledge, pull requests merged in 2021-02, with the labels that each got.

#279 fix the visibility of the preview area
  attachment_preview/static/src/scss/attachment_preview.scss
Labels: approved, bot is merging ⏳, ready to merge

#284 [12.0][FIX] document_page_approval: Add correct followers in history pages
  document_page_approval/models/document_page_history.py
  document_page_approval/readme/CONTRIBUTORS.rst
  document_page_approval/tests/test_document_page_approval.py
Labels: approved, bot is merging ⏳

#285 [13.0][FIX] document_page_approval: Add correct followers in history pages
  document_page_approval/models/document_page_history.py
  document_page_approval/readme/CONTRIBUTORS.rst
  document_page_approval/tests/test_document_page_approval.py
Labels: bot is merging ⏳

#273 [13.0][FIX] document_page_approval: Add no-update=1 in xml data
  document_page_approval/data/email_template.xml
Labels: approved, bot is merging ⏳, ready to merge
