Repository OCA/knowledge, pull requests merged in 2021-08, with the labels that each got.

#294 [FIX] attachment_preview: start needs to return a promise
  attachment_preview/README.rst
  attachment_preview/readme/CONTRIBUTORS.rst
  attachment_preview/static/src/js/attachment_preview.js
Labels: approved, ready to merge, bot is merging ⏳

#214 [IMP] document_ocr: handle invalid data in attachments gracefully
  document_ocr/models/ir_attachment.py
Labels: needs review, approved

#128 [ADD] help_popup_document_page
  help_popup_document_page/README.rst
  help_popup_document_page/__init__.py
  help_popup_document_page/__openerp__.py
  help_popup_document_page/data/document_page.xml
  help_popup_document_page/demo/document_page.xml
  help_popup_document_page/hooks.py
  help_popup_document_page/models/__init__.py
  help_popup_document_page/models/document_page.py
  help_popup_document_page/models/ir_actions_act_window.py
  help_popup_document_page/security/res_groups.xml
  help_popup_document_page/static/description/icon.png
  help_popup_document_page/tests/__init__.py
  help_popup_document_page/tests/test_help_popup_document_page.py
  help_popup_document_page/views/document_page.xml
  oca_dependencies.txt
Labels: needs review

#293 [13.0][FIX] document_page_approval: Delete diff in email_template to prevent errors in some cases
  document_page_approval/data/email_template.xml
Labels: approved, bot is merging ⏳

#253 [12.0][ADD] attachment_category
  attachment_category/README.rst
  attachment_category/__init__.py
  attachment_category/__manifest__.py
  attachment_category/models/__init__.py
  attachment_category/models/ir_attachment.py
  attachment_category/models/ir_attachment_category.py
  attachment_category/readme/CONTRIBUTORS.rst
  attachment_category/readme/DESCRIPTION.rst
  attachment_category/readme/USAGE.rst
  attachment_category/security/ir_attachment_category.xml
  attachment_category/static/description/icon.png
  attachment_category/static/description/index.html
  attachment_category/views/ir_attachment.xml
  attachment_category/views/ir_attachment_category.xml
  setup/attachment_category/odoo/addons/attachment_category
  setup/attachment_category/setup.py
Labels: approved, bot is merging ⏳

#178 [MIG] attachment_edit to 10.0
  attachment_action/README.rst
  attachment_action/__init__.py
  attachment_action/__manifest__.py
  attachment_action/readme/CONTRIBUTORS.rst
  attachment_action/readme/DESCRIPTION.rst
  attachment_action/readme/USAGE.rst
  attachment_action/static/description/icon.png
  attachment_action/static/description/index.html
  attachment_action/static/src/css/attachment_action.css
  attachment_action/static/src/xml/attachment_action.xml
  attachment_action/views/templates.xml
  attachment_edit/README.rst
  attachment_edit/__init__.py
  attachment_edit/__manifest__.py
  attachment_edit/i18n/de.po
  attachment_edit/i18n/it.po
  attachment_edit/i18n/sl.po
  attachment_edit/i18n/zh_CN.po
  attachment_edit/models/__init__.py
  attachment_edit/models/ir_attachment.py
  attachment_edit/readme/CONTRIBUTORS.rst
  attachment_edit/readme/DESCRIPTION.rst
  attachment_edit/readme/USAGE.rst
  attachment_edit/static/description/icon.png
  attachment_edit/static/description/index.html
  attachment_edit/static/src/js/attachment_edit.js
  attachment_edit/static/src/xml/attachment_edit.xml
  attachment_edit/tests/__init__.py
  attachment_edit/tests/test_attachment_edit.py
  attachment_edit/views/ir_attachment.xml
  attachment_edit/views/templates.xml
Labels: needs review, bot is merging ⏳
