Repository OCA/knowledge, pull requests merged in 2022-11, with the labels that each got.

#371 Update template
  .copier-answers.yml
  .github/workflows/test.yml
  .gitignore
  .pre-commit-config.yaml
  .pylintrc
  .pylintrc-mandatory
  .travis.yml
  README.md
  document_page/__manifest__.py
  knowledge/__manifest__.py
Labels: approved, bot is merging ⏳

#370 [FIX] document_page_approval: no "order" parameter in One2many field
  document_page_approval/models/document_page.py
Labels: bug, needs review, approved, ready to merge, bot is merging ⏳

#380 [15.0][FIX] document_page_group: Issue with logs spamming field error
  document_page_group/models/document_page.py
Labels: bot is merging ⏳
