Repository OCA/knowledge, pull requests merged in 2022-12, with the labels that each got.

#383 [16.0][MIG] document page group: Migration to 16.0
  document_page_group/README.rst
  document_page_group/__init__.py
  document_page_group/__manifest__.py
  document_page_group/i18n/document_page_group.pot
  document_page_group/i18n/es.po
  document_page_group/i18n/sl.po
  document_page_group/models/__init__.py
  document_page_group/models/document_page.py
  document_page_group/readme/CONTRIBUTORS.rst
  document_page_group/readme/DESCRIPTION.rst
  document_page_group/security/document_page_security.xml
  document_page_group/static/description/icon.png
  document_page_group/static/description/index.html
  document_page_group/tests/__init__.py
  document_page_group/tests/test_document_page_group.py
  document_page_group/views/document_page.xml
  setup/document_page_group/odoo/addons/document_page_group
  setup/document_page_group/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#390 [16.0][FIX] document_knowledge: Error in data-key res_config
  document_knowledge/views/res_config.xml
Labels: bot is merging ⏳

#325 [15.0] [MIG] document_page_project
  document_page_project/README.rst
  document_page_project/__init__.py
  document_page_project/__manifest__.py
  document_page_project/i18n/document_page_project.pot
  document_page_project/i18n/es.po
  document_page_project/i18n/he_IL.po
  document_page_project/i18n/hr.po
  document_page_project/models/__init__.py
  document_page_project/models/document_page.py
  document_page_project/models/project_project.py
  document_page_project/readme/CONTRIBUTORS.rst
  document_page_project/readme/DESCRIPTION.rst
  document_page_project/readme/USAGE.rst
  document_page_project/static/description/icon.png
  document_page_project/static/description/index.html
  document_page_project/tests/__init__.py
  document_page_project/tests/test_project_project.py
  document_page_project/views/document_page_views.xml
  document_page_project/views/project_project_views.xml
  setup/document_page_project/odoo/addons/document_page_project
  setup/document_page_project/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#391 [16.0][MIG] attachment_zipped_download: Migration to 16.0
  attachment_zipped_download/README.rst
  attachment_zipped_download/__init__.py
  attachment_zipped_download/__manifest__.py
  attachment_zipped_download/controllers/__init__.py
  attachment_zipped_download/controllers/main.py
  attachment_zipped_download/i18n/attachment_zipped_download.pot
  attachment_zipped_download/i18n/es.po
  attachment_zipped_download/models/__init__.py
  attachment_zipped_download/models/ir_attachment.py
  attachment_zipped_download/readme/CONTRIBUTORS.rst
  attachment_zipped_download/readme/DESCRIPTION.rst
  attachment_zipped_download/readme/USAGE.rst
  attachment_zipped_download/static/description/icon.png
  attachment_zipped_download/static/description/index.html
  attachment_zipped_download/tests/__init__.py
  attachment_zipped_download/tests/test_attachment_zipped_download.py
  attachment_zipped_download/views/ir_attachment_view.xml
  setup/attachment_zipped_download/odoo/addons/attachment_zipped_download
  setup/attachment_zipped_download/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#393 [15.0][IMP] document_page_reference: auto-fill reference when not supplied.
  document_page_reference/models/document_page.py
  document_page_reference/tests/test_document_reference.py
  document_page_reference/views/document_page.xml
Labels: approved, bot is merging ⏳
