Repository OCA/knowledge, pull requests merged in 2022-05, with the labels that each got.

#340 [15.0][IMP] document_page: add side search panel with categories.
  document_page/readme/CONTRIBUTORS.rst
  document_page/views/document_page.xml
Labels: approved, bot is merging ⏳

#341 [IMP]document_page_tag: Color column in tag tree view
  document_page_tag/views/document_page_tag.xml
Labels: approved, bot is merging ⏳

#342 [IMP]document_page_tag: Color column in tag tree view
  document_page_tag/views/document_page_tag.xml
Labels: bot is merging ⏳

#346 [ADD]document_page_access_group: Add access groups to document pages
  document_page_access_group/__init__.py
  document_page_access_group/__manifest__.py
  document_page_access_group/models/__init__.py
  document_page_access_group/models/document_page.py
  document_page_access_group/readme/CONTRIBUTORS.rst
  document_page_access_group/readme/DESCRIPTION.rst
  document_page_access_group/readme/USAGE.rst
  document_page_access_group/security/security.xml
  document_page_access_group/static/description/icon.png
  document_page_access_group/views/document_page.xml
  setup/document_page_access_group/odoo/addons/document_page_access_group
  setup/document_page_access_group/setup.py
Labels: approved, bot is merging ⏳

#345 [14.0][FIX]: change the priority views form.
  document_page/views/document_page.xml
  document_page/views/document_page_category.xml
Labels: approved, ready to merge, bot is merging ⏳
