Repository OCA/knowledge, pull requests merged in 2023-04, with the labels that each got.

#376 [14.0][FIX] document_page_reference: assure content or content_parsed is visible
  document_page_reference/models/document_page.py
  document_page_reference/views/document_page.xml
Labels: bug, bot is merging ⏳, stale

#377 [15.0][FIX] document_page_reference: assure content or content_parsed is visible
  document_page_reference/models/document_page.py
  document_page_reference/views/document_page.xml
Labels: bug, bot is merging ⏳, stale

#363 [15.0][MIG] attachment_preview: Migration to version 15.0
  attachment_preview/README.rst
  attachment_preview/__init__.py
  attachment_preview/__manifest__.py
  attachment_preview/i18n/attachment_preview.pot
  attachment_preview/i18n/de.po
  attachment_preview/i18n/es.po
  attachment_preview/i18n/it.po
  attachment_preview/i18n/nl.po
  attachment_preview/i18n/pt_BR.po
  attachment_preview/i18n/pt_PT.po
  attachment_preview/i18n/sl.po
  attachment_preview/i18n/tr.po
  attachment_preview/i18n/vi_VN.po
  attachment_preview/i18n/zh_CN.po
  attachment_preview/models/__init__.py
  attachment_preview/models/ir_attachment.py
  attachment_preview/readme/CONTRIBUTORS.rst
  attachment_preview/readme/CREDITS.rst
  attachment_preview/readme/DESCRIPTION.rst
  attachment_preview/readme/INSTALL.rst
  attachment_preview/readme/USAGE.rst
  attachment_preview/static/description/icon.png
  attachment_preview/static/description/index.html
  attachment_preview/static/description/screenshot-paginator.png
  attachment_preview/static/description/screenshot-split.png
  attachment_preview/static/lib/ViewerJS/compatibility.js
  attachment_preview/static/lib/ViewerJS/example.local.css
  attachment_preview/static/lib/ViewerJS/images/kogmbh.png
  attachment_preview/static/lib/ViewerJS/images/nlnet.png
  attachment_preview/static/lib/ViewerJS/images/texture.png
  attachment_preview/static/lib/ViewerJS/images/toolbarButton-download.png
  attachment_preview/static/lib/ViewerJS/images/toolbarButton-fullscreen.png
  attachment_preview/static/lib/ViewerJS/images/toolbarButton-menuArrows.png
  attachment_preview/static/lib/ViewerJS/images/toolbarButton-pageDown.png
  attachment_preview/static/lib/ViewerJS/images/toolbarButton-pageUp.png
  attachment_preview/static/lib/ViewerJS/images/toolbarButton-presentation.png
  attachment_preview/static/lib/ViewerJS/images/toolbarButton-zoomIn.png
  attachment_preview/static/lib/ViewerJS/images/toolbarButton-zoomOut.png
  attachment_preview/static/lib/ViewerJS/index.html
  attachment_preview/static/lib/ViewerJS/pdf.js
  attachment_preview/static/lib/ViewerJS/pdf.worker.js
  attachment_preview/static/lib/ViewerJS/pdfjsversion.js
  attachment_preview/static/lib/ViewerJS/text_layer_builder.js
  attachment_preview/static/lib/ViewerJS/ui_utils.js
  attachment_preview/static/lib/ViewerJS/webodf.js
  attachment_preview/static/src/js/attachmentPreviewWidget.esm.js
  attachment_preview/static/src/js/components/chatter/chatter.esm.js
  attachment_preview/static/src/js/models/attachment_card/attachment_card.esm.js
  attachment_preview/static/src/js/viewerjs_tweaks.js
  attachment_preview/static/src/scss/attachment_preview.scss
  attachment_preview/static/src/xml/attachment_preview.xml
  attachment_preview/tests/__init__.py
  attachment_preview/tests/test_attachment_preview.py
  setup/attachment_preview/odoo/addons/attachment_preview
  setup/attachment_preview/setup.py
Labels: needs review, approved, migration, bot is merging ⏳

#409 [15.0][FIX] document_page_approval: Change mail template expressions
  document_page_approval/data/email_template.xml
Labels: bug, needs review, approved, bot is merging ⏳

#410 [16.0][FIX] document_page_approval: Change mail template expressions
  document_page_approval/data/email_template.xml
Labels: approved, bot is merging ⏳
