Repository OCA/knowledge, pull requests merged in 2023-08, with the labels that each got.

#360 [14.0][MIG] attachment_preview: Migration to version 14.0
  attachment_preview/README.rst
  attachment_preview/__init__.py
  attachment_preview/__manifest__.py
  attachment_preview/i18n/attachment_preview.pot
  attachment_preview/i18n/de.po
  attachment_preview/i18n/es.po
  attachment_preview/i18n/it.po
  attachment_preview/i18n/nl.po
  attachment_preview/i18n/pt_BR.po
  attachment_preview/i18n/pt_PT.po
  attachment_preview/i18n/sl.po
  attachment_preview/i18n/tr.po
  attachment_preview/i18n/zh_CN.po
  attachment_preview/models/__init__.py
  attachment_preview/models/ir_attachment.py
  attachment_preview/readme/CONTRIBUTORS.rst
  attachment_preview/readme/CREDITS.rst
  attachment_preview/readme/DESCRIPTION.rst
  attachment_preview/readme/INSTALL.rst
  attachment_preview/readme/USAGE.rst
  attachment_preview/static/description/icon.png
  attachment_preview/static/description/index.html
  attachment_preview/static/description/screenshot-paginator.png
  attachment_preview/static/description/screenshot-split.png
  attachment_preview/static/lib/ViewerJS/compatibility.js
  attachment_preview/static/lib/ViewerJS/example.local.css
  attachment_preview/static/lib/ViewerJS/images/kogmbh.png
  attachment_preview/static/lib/ViewerJS/images/nlnet.png
  attachment_preview/static/lib/ViewerJS/images/texture.png
  attachment_preview/static/lib/ViewerJS/images/toolbarButton-download.png
  attachment_preview/static/lib/ViewerJS/images/toolbarButton-fullscreen.png
  attachment_preview/static/lib/ViewerJS/images/toolbarButton-menuArrows.png
  attachment_preview/static/lib/ViewerJS/images/toolbarButton-pageDown.png
  attachment_preview/static/lib/ViewerJS/images/toolbarButton-pageUp.png
  attachment_preview/static/lib/ViewerJS/images/toolbarButton-presentation.png
  attachment_preview/static/lib/ViewerJS/images/toolbarButton-zoomIn.png
  attachment_preview/static/lib/ViewerJS/images/toolbarButton-zoomOut.png
  attachment_preview/static/lib/ViewerJS/index.html
  attachment_preview/static/lib/ViewerJS/pdf.js
  attachment_preview/static/lib/ViewerJS/pdf.worker.js
  attachment_preview/static/lib/ViewerJS/pdfjsversion.js
  attachment_preview/static/lib/ViewerJS/text_layer_builder.js
  attachment_preview/static/lib/ViewerJS/ui_utils.js
  attachment_preview/static/lib/ViewerJS/webodf.js
  attachment_preview/static/src/js/attachment_preview.js
  attachment_preview/static/src/js/viewerjs_tweaks.js
  attachment_preview/static/src/scss/attachment_preview.scss
  attachment_preview/static/src/xml/attachment_preview.xml
  attachment_preview/templates/assets.xml
  attachment_preview/tests/__init__.py
  attachment_preview/tests/test_attachment_preview.py
  setup/attachment_preview/odoo/addons/attachment_preview
  setup/attachment_preview/setup.py
Labels: needs review, approved, migration, ready to merge, bot is merging ⏳

#426 [14.0][FIX] document_page: Stored XSS
  document_page/__manifest__.py
  document_page/migrations/14.0.1.2.4/post-migration.py
  document_page/models/document_page.py
  document_page/models/document_page_history.py
  document_page/tests/__init__.py
  document_page/tests/test_document_page.py
  document_page/tests/test_document_page_content_sanitized.py
  document_page_approval/tests/test_document_page_approval.py
  document_page_reference/tests/test_document_reference.py
Labels: bug, needs review, approved, bot is merging ⏳

#408 [14.0][FIX] document_page_project: fix permissions for project users
  document_page_project/models/project_project.py
Labels: approved, bot is merging ⏳, stale

#427 [16.0][FIX] attachment_zipped_download: zip allowed document only
  attachment_zipped_download/models/ir_attachment.py
  attachment_zipped_download/tests/test_attachment_zipped_download.py
Labels: approved, bot is merging ⏳
