Repository OCA/knowledge, pull requests merged in 2024-02, with the labels that each got.

#444 [16.0][ADD]document_url_google_drive
  document_url_google_drive/README.rst
  document_url_google_drive/__init__.py
  document_url_google_drive/__manifest__.py
  document_url_google_drive/models/__init__.py
  document_url_google_drive/models/res_config_settings.py
  document_url_google_drive/models/res_users.py
  document_url_google_drive/readme/CONFIGURE.md
  document_url_google_drive/readme/CONTRIBUTORS.md
  document_url_google_drive/readme/DESCRIPTION.md
  document_url_google_drive/readme/USAGE.md
  document_url_google_drive/readme/newsfragments/.gitkeep
  document_url_google_drive/static/description/banner.png
  document_url_google_drive/static/description/icon.png
  document_url_google_drive/static/description/icon.svg
  document_url_google_drive/static/description/index.html
  document_url_google_drive/static/img/gdrive_link.png
  document_url_google_drive/static/img/google_api_settings.png
  document_url_google_drive/static/src/img/logo-google-drive.png
  document_url_google_drive/static/src/js/attachment_google_picker.esm.js
  document_url_google_drive/static/src/xml/attachment_google_picker.xml
  document_url_google_drive/static/src/xml/google_picker_url.xml
  document_url_google_drive/tests/__init__.py
  document_url_google_drive/tests/test_document_url.py
  document_url_google_drive/views/res_config_settings_view.xml
  document_url_google_drive/views/res_users_view.xml
  document_url_google_drive/wizard/__init__.py
  document_url_google_drive/wizard/document_url.py
  setup/document_url_google_drive/odoo/addons/document_url_google_drive
  setup/document_url_google_drive/setup.py
Labels: approved, ready to merge, bot is merging ⏳

#459 [16.0][FIX] document_url_google_drive
  document_url_google_drive/README.rst
  document_url_google_drive/readme/CONFIGURE.md
  document_url_google_drive/readme/CONTRIBUTORS.md
  document_url_google_drive/static/description/index.html
Labels: bot is merging ⏳

#460 [16.0][FIX]document_url
  document_url/static/src/js/url.esm.js
  document_url/static/src/xml/url.xml
Labels: approved, ready to merge

#461 [14.0] [FIX] attachment_preview: fix get_binary_extension
  attachment_preview/models/ir_attachment.py
  attachment_preview/tests/test_attachment_preview.py
Labels: approved, ready to merge

#430 [16.0][FIX] attachment_zipped_download: create temporary file to stream
  attachment_zipped_download/controllers/main.py
Labels: approved, bot is merging ⏳
