Repository OCA/knowledge, pull requests merged in 2024-04, with the labels that each got.

#470 [16.0][MIG] document_page_access_group: Migration to 16.0
  document_page_access_group/README.rst
  document_page_access_group/__init__.py
  document_page_access_group/__manifest__.py
  document_page_access_group/i18n/document_page_access_group.pot
  document_page_access_group/i18n/es.po
  document_page_access_group/i18n/it.po
  document_page_access_group/models/__init__.py
  document_page_access_group/models/document_page.py
  document_page_access_group/readme/CONTRIBUTORS.rst
  document_page_access_group/readme/DESCRIPTION.rst
  document_page_access_group/readme/USAGE.rst
  document_page_access_group/security/security.xml
  document_page_access_group/static/description/icon.png
  document_page_access_group/static/description/index.html
  document_page_access_group/tests/__init__.py
  document_page_access_group/tests/test_document_page_access_group.py
  document_page_access_group/views/document_page.xml
  setup/document_page_access_group/odoo/addons/document_page_access_group
  setup/document_page_access_group/setup.py
Labels: approved, bot is merging ⏳

#471 [17.0][MIG] document_page_access_group: Migration to 17.0
  document_page_access_group/README.rst
  document_page_access_group/__init__.py
  document_page_access_group/__manifest__.py
  document_page_access_group/i18n/document_page_access_group.pot
  document_page_access_group/i18n/es.po
  document_page_access_group/i18n/it.po
  document_page_access_group/models/__init__.py
  document_page_access_group/models/document_page.py
  document_page_access_group/pyproject.toml
  document_page_access_group/readme/CONTRIBUTORS.md
  document_page_access_group/readme/DESCRIPTION.md
  document_page_access_group/readme/USAGE.md
  document_page_access_group/security/security.xml
  document_page_access_group/static/description/icon.png
  document_page_access_group/static/description/index.html
  document_page_access_group/tests/__init__.py
  document_page_access_group/tests/test_document_page_access_group.py
  document_page_access_group/views/document_page.xml
Labels: approved, bot is merging ⏳

#472 [17.0][FIX] document_page: draft summary widget
  document_page/views/document_page.xml
Labels: approved, bot is merging ⏳

#473 [15.0][MIG] attachment_zipped_download: Migration to 15.0
  attachment_zipped_download/README.rst
  attachment_zipped_download/__init__.py
  attachment_zipped_download/__manifest__.py
  attachment_zipped_download/controllers/__init__.py
  attachment_zipped_download/controllers/main.py
  attachment_zipped_download/i18n/attachment_zipped_download.pot
  attachment_zipped_download/i18n/es.po
  attachment_zipped_download/i18n/fr.po
  attachment_zipped_download/i18n/it.po
  attachment_zipped_download/models/__init__.py
  attachment_zipped_download/models/ir_attachment.py
  attachment_zipped_download/models/ir_attachment_action_download.py
  attachment_zipped_download/readme/CONTRIBUTORS.rst
  attachment_zipped_download/readme/DESCRIPTION.rst
  attachment_zipped_download/readme/USAGE.rst
  attachment_zipped_download/static/description/icon.png
  attachment_zipped_download/static/description/index.html
  attachment_zipped_download/tests/__init__.py
  attachment_zipped_download/tests/models/__init__.py
  attachment_zipped_download/tests/models/res_partner.py
  attachment_zipped_download/tests/test_attachment_zipped_download.py
  attachment_zipped_download/tests/test_ir_attachment_action_download.py
  attachment_zipped_download/views/ir_attachment_view.xml
  setup/attachment_zipped_download/odoo/addons/attachment_zipped_download
  setup/attachment_zipped_download/setup.py
Labels: approved, bot is merging ⏳

#474 [14.0][IMP] document_page: add Browse Wiki Content view Kanban
  document_page/models/document_page.py
  document_page/static/src/js/document_page_kanban.js
  document_page/views/document_page.xml
  document_page/views/document_page_assets.xml
  document_page/views/document_page_category.xml
Labels: enhancement, needs review, approved, bot is merging ⏳

#477 [14.0][REF] document_page: set title attribute in <i> tag
  document_page/views/document_page_category.xml
Labels: bot is merging ⏳

#479 [14.0][FIX] document_page_approval: Add correct followers in history pages
  document_page_approval/models/document_page_history.py
  document_page_approval/readme/CONTRIBUTORS.rst
  document_page_approval/tests/test_document_page_approval.py
Labels: bot is merging ⏳

#481 [16.0][FIX] document_page_approval: Add correct followers in history pages
  document_page_approval/models/document_page_history.py
  document_page_approval/readme/CONTRIBUTORS.rst
  document_page_approval/tests/test_document_page_approval.py
Labels: bot is merging ⏳

#480 [15.0][FIX] document_page_approval: Add correct followers in history pages
  document_page_approval/models/document_page_history.py
  document_page_approval/readme/CONTRIBUTORS.rst
  document_page_approval/tests/test_document_page_approval.py
Labels: bot is merging ⏳
