Repository OCA/knowledge, pull requests merged in 2025-03, with the labels that each got.

#521 [18.0][FIX] document_page: Remove pre-commit warning log
  document_page/static/src/js/document_page_kanban_view.esm.js
Labels: bot is merging ⏳

#500 Update README.md - fix typos
  README.md
Labels: bot is merging ⏳, stale

#483 [17.0][MIG] Migration attachment_category to v17.0
  attachment_category/README.rst
  attachment_category/__init__.py
  attachment_category/__manifest__.py
  attachment_category/i18n/attachment_category.pot
  attachment_category/i18n/es.po
  attachment_category/i18n/it.po
  attachment_category/models/__init__.py
  attachment_category/models/ir_attachment.py
  attachment_category/models/ir_attachment_category.py
  attachment_category/pyproject.toml
  attachment_category/readme/CONTRIBUTORS.md
  attachment_category/readme/DESCRIPTION.md
  attachment_category/readme/USAGE.md
  attachment_category/security/ir_attachment_category.xml
  attachment_category/static/description/icon.png
  attachment_category/static/description/index.html
  attachment_category/views/ir_attachment.xml
  attachment_category/views/ir_attachment_category.xml
Labels: approved, bot is merging ⏳, stale

#530 [16.0][FIX] document_page_approval: Add Change Request Manager rule
  document_page_approval/security/document_page_security.xml
  document_page_approval/views/document_page_approval.xml
Labels: approved, bot is merging ⏳

#532 [16.0][IMP] document_page: warning multi create
  document_page/models/document_page.py
Labels: approved, bot is merging ⏳

#523 [18.0][MIG] document_page_access_group: Migration to 18.0
  document_page_access_group/README.rst
  document_page_access_group/__init__.py
  document_page_access_group/__manifest__.py
  document_page_access_group/i18n/ca.po
  document_page_access_group/i18n/document_page_access_group.pot
  document_page_access_group/i18n/es.po
  document_page_access_group/i18n/it.po
  document_page_access_group/models/__init__.py
  document_page_access_group/models/document_page.py
  document_page_access_group/pyproject.toml
  document_page_access_group/readme/CONTRIBUTORS.md
  document_page_access_group/readme/DESCRIPTION.md
  document_page_access_group/readme/USAGE.md
  document_page_access_group/security/security.xml
  document_page_access_group/static/description/icon.png
  document_page_access_group/static/description/index.html
  document_page_access_group/tests/__init__.py
  document_page_access_group/tests/common.py
  document_page_access_group/tests/test_document_page_access_group.py
  document_page_access_group/views/document_page.xml
Labels: approved, ready to merge, bot is merging ⏳

#531 [17.0][FIX] document_page_approval: Add Change Request Manager rule
  document_page_approval/security/document_page_security.xml
  document_page_approval/views/document_page_approval.xml
Labels: approved, ready to merge, bot is merging ⏳

#517 [FIX] document_knowledge: Use different path to avoid collision with odoo documents
  document_knowledge/views/document_knowledge.xml
Labels: approved, ready to merge, bot is merging ⏳
